### ISSUE TITLE
tensorflowa dönüştürme 

### ISSUE THREAD

**Issue by YCAyca** [yasarniyazoglu/yolov4-android-tflite#1]
Merhaba, 

python save_model.py --weights ./data/yolov4_roadsign_4000.weights --output ./checkpoints/yolov4-416 --input_size 416 --model yolov4 --framework tflite komutunu kullanıp yolov4 te eğitilmiş modelimi tensorflow modeline çevirmeye çalışırken aşağıdaki hatayı alıyorum. Bundan önce Unable to create file './checkpoints/yolov4-416' hatası alıyordum o yüzden manuel olarak oluşturdum bu klasörü. Şimdi de permission denied diyor anaconda promptu admin olarak açmama ve aslında dosyanın izinleri açık olmasına rağmen. Yardımcı olabilir misiniz? 

OSError: Unable to create file (unable to open file: name = './checkpoints/yolov4-416', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

Teşekkürler

**Comment by yasarniyazoglu** [comment]
Merhaba. Coco.names dosyasini düzelemediyseniz düzenleyin. Save model.py
dosyasini acin ve orda --weight icin adres var oraya kendi weight
dosyanizin adini yazin ve deneyin. Extra olarak hatanin tam çıktısını
atarmisiniz

31 Oca 2022 Pzt 23:55 tarihinde Yağmur Çiğdem Aktaş <
***@***.***> şunu yazdı:

**Comment by YCAyca** [comment]
![image](https://user-images.githubusercontent.com/20625822/151876730-bec68d33-a354-4be5-917d-bc29a528f351.png)

weights adresini değiştirmeyi unutmuşum teşekkürler. fakat sorun çözülmedi hala aynı hata geliyor.

eğer manuel oluşturduğum './checkpoints/yolov4-416 klasörünü silersem de aşağıdaki error geliyor

![image](https://user-images.githubusercontent.com/20625822/151876920-b6bd2255-b4ca-4677-bbed-28dd8fbc707e.png)

**Comment by yasarniyazoglu** [comment]
pip install h5py yapın olmassa conda install h5py dneyin. yine olmassa ben
tekar kendim denicem. ama merak etmeyin çözeriz

Yağmur Çiğdem Aktaş ***@***.***>, 1 Şub 2022 Sal, 00:35
tarihinde şunu yazdı:

**Comment by YCAyca** [comment]
yüklüymüş bu işe yaramadı fakat sorun çözüldü. versiyon farklılığından kaynaklanıyordu büyük ihtimalle dün nedense bi türlü 3.6.15 ile env kuramamıştım paket bulunamadı diyordu bugün direk kuruldu. Bilgisayarı açıp kapayınca anacondanın channelarına ne oluyor olabilir bilemedim ama çalışıyor yani çok teşekkürler
