### ISSUE TITLE
TF detect keeps stopping

### ISSUE THREAD

**Issue by YCAyca** [yasarniyazoglu/yolov4-android-tflite#2]
merhaba, tflite e çevirme işlemi tamamlandı fakat android app te çalıştıramıyorum nedense.
Android telefonum olmadığı için emulator kullanıyorum, build işlemini 10.0 Q versiyonunda yaptığım için yine 10.0 Q sürümüne sahip bir telefon simülatorü yarattım. mainactivity ve detectoractivity de söylediğiniz değişiklikleri yaptım, kod build oluyor fakat emulatorde açılmıyor app. Acaba yardımcı olabileceğiniz bir konu mu?
Genel olarak dosyalarımın konumunu ve içeriğini paylaşıyorum:

![image](https://user-images.githubusercontent.com/20625822/152553584-d87164d1-5133-43a6-81e5-24e2329119ed.png)

![image](https://user-images.githubusercontent.com/20625822/152553633-26c49137-47e5-41f8-9f94-7df8ba9c8acb.png)

![image](https://user-images.githubusercontent.com/20625822/152553677-96ca5eb9-59ce-439c-a66c-f94a576fe526.png)

![image](https://user-images.githubusercontent.com/20625822/152553752-03548b0e-9224-4bd8-b7b5-52ea6b2dbc51.png)

![image](https://user-images.githubusercontent.com/20625822/152554117-1c58a394-962b-4021-b2b3-99d0ecf84058.png)

![image](https://user-images.githubusercontent.com/20625822/152554167-528d39eb-1d21-4e51-a819-a9f46bfe65a1.png)

![image](https://user-images.githubusercontent.com/20625822/152554194-3920de31-59c4-4fe3-a79d-a2bedd6e045f.png)

bir de sebebini anlamadığım bir şekilde labelmap.txt diye bir file çıkıp duruyor. DetectorTest kodunda kullanılıyor ama benim anladığım biz o kodu kullanmıyoruz ama acaba anlamadığım bir kısım mı var diye eklemek istedim:

![image](https://user-images.githubusercontent.com/20625822/152553967-84376f2a-de33-4397-ac83-228e540270cf.png)

**Comment by YCAyca** [comment]
ki sonradan app kısmına geçmeden önce tflite modelim çalışıyor mu diye kontrol etmek aklıma geldi ve çalışmıyormuş... 

python detect.py --weights ./checkpoints/yolov4-416.tflite --size 416 --model yolov4 --image ./data/1.jpg --framework tflite 
komutunu kullandım ve aşağıdaki sonucu aldım 

![image](https://user-images.githubusercontent.com/20625822/152562114-7254c4b0-acde-4833-8945-aafd86c4f363.png)

**Comment by yasarniyazoglu** [comment]
Tam olarak neler olduğunu anlamam için görmem lazım. Sizin icinde uygunsa
mail atın bana . Discord linki paylasayim ordan bakalim

4 Şub 2022 Cum 19:07 tarihinde Yağmur Çiğdem Aktaş ***@***.***>
şunu yazdı:

**Comment by YCAyca** [comment]
tabii uygun

**Comment by yasarniyazoglu** [comment]
https://discord.gg/8bQWT6Zw

4 Şub 2022 Cum 23:21 tarihinde Yağmur Çiğdem Aktaş ***@***.***>
şunu yazdı:

**Comment by YCAyca** [comment]
hımm sanırım davetin süresi dolmuş giriş yapamadığımı söyledi bu sebepten. isterseniz müsait olduğunuz bir zamana göre ayarlayalım ben de kendimi ona göre ayarlarım?

**Comment by yasarniyazoglu** [comment]
Bana yarın öğleden önce mail atarsaniz yardimci olurum.

7 Şub 2022 Pzt 22:26 tarihinde Yağmur Çiğdem Aktaş ***@***.***>
şunu yazdı:

**Comment by YCAyca** [comment]
İşte olduğum için yazamıyorum o saate kadar fakat yarın akşam 7 gibi müsait olur muydunuz?

**Comment by yasarniyazoglu** [comment]
Bende çalışıyorum . 7 gibi yolda oluyorum genelde ama 7 den sonraki saatler
musait olurum.

8 Şub 2022 Sal 11:20 tarihinde Yağmur Çiğdem Aktaş ***@***.***>
şunu yazdı:

**Comment by YCAyca** [comment]
merhaba simulatorde hala calismiyor fakat modeli tflite e cevirirken float32 yerine float16 yi kullaninca telefonda calisti. Bu cevrimdeki float8 float16 float32 farki tam olarak nedir biliyor musunuz?

**Comment by yasarniyazoglu** [comment]
Merhaba. Bildigim kadari ile hassasiyet degeri. Yani float 8 e cevirince
hız yükseliyor dogruluk azliyor. 32 de ise hiz yavas dogruluk yuksek diye
biliyorum

13 Şub 2022 Paz 23:20 tarihinde Yağmur Çiğdem Aktaş <
***@***.***> şunu yazdı:

**Comment by YCAyca** [comment]
cok tesekkurler cevap icin
